-- Migration: 048_benefit_card_presets.sql
-- Description: Creates benefit_card_presets table with single active default constraint and seeds initial system presets with Masonry Flow as active default (44px icon size, subtle 3D lift, auto uniform height).

CREATE TABLE IF NOT EXISTS benefit_card_presets (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    short_name VARCHAR(60) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    is_default BOOLEAN NOT NULL DEFAULT false,
    is_custom BOOLEAN NOT NULL DEFAULT false,
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_single_default_benefit_card_preset
ON benefit_card_presets (is_default)
WHERE is_default = true;

CREATE INDEX IF NOT EXISTS idx_benefit_card_presets_custom ON benefit_card_presets(is_custom);

-- Seed System Presets (with Masonry Flow as default: 44px icons, subtle 3D lift, auto height)
INSERT INTO benefit_card_presets (id, name, short_name, description, is_default, is_custom, config, created_at, updated_at)
VALUES
(
    'masonry-flow',
    'Masonry Flow (Dynamic)',
    'Masonry Flow',
    '3-column fluid masonry, natural card heights, zero wasted space',
    true,
    false,
    '{
        "shape": "rounded",
        "layout": "masonry",
        "borderWidth": 1,
        "borderStyle": "solid",
        "elevation": "lift",
        "uniformHeight": 0,
        "iconSize": 44,
        "imageFit": "contain",
        "iconPadShape": "box",
        "titleSize": 10.5,
        "titleWeight": "bold",
        "titleColor": "#0f172a",
        "textWrap": "wrap",
        "valueBadgeStyle": "red",
        "coverageSize": 11,
        "coverageColor": "#10b981",
        "descSize": 9,
        "descColor": "#64748b",
        "costSize": 9,
        "costColor": "#b91c1c",
        "costBgColor": "#fee2e2",
        "showDescription": true,
        "showCoverage": true,
        "showCost": true,
        "bgColor": "#ffffff",
        "borderColor": "#e2e8f0",
        "textColor": "#0f172a",
        "accentColor": "#dc2626",
        "columns": 3,
        "layoutMode": "masonry",
        "textDensity": "compact",
        "cardStyle": "standard",
        "rowHeight": 66
    }'::jsonb,
    NOW(),
    NOW()
),
(
    'compact-minimal',
    'Compact Minimalist (1-Page Fit)',
    'Compact Minimal',
    'Ultra-compact single-line rows, fits 35+ items cleanly on 1 page',
    false,
    false,
    '{
        "shape": "square",
        "layout": "compact",
        "borderWidth": 1,
        "borderStyle": "solid",
        "elevation": "flat",
        "uniformHeight": 38,
        "iconSize": 18,
        "imageFit": "contain",
        "iconPadShape": "none",
        "titleSize": 9.5,
        "titleWeight": "semibold",
        "titleColor": "#0f172a",
        "textWrap": "truncate",
        "valueBadgeStyle": "subtle",
        "coverageSize": 9.5,
        "coverageColor": "#10b981",
        "descSize": 8.5,
        "descColor": "#64748b",
        "costSize": 8.5,
        "costColor": "#475569",
        "costBgColor": "#f1f5f9",
        "showDescription": false,
        "showCoverage": true,
        "showCost": true,
        "bgColor": "#ffffff",
        "borderColor": "#f1f5f9",
        "textColor": "#0f172a",
        "accentColor": "#dc2626",
        "columns": 3,
        "layoutMode": "masonry",
        "textDensity": "compact",
        "cardStyle": "minimal",
        "rowHeight": 40
    }'::jsonb,
    NOW(),
    NOW()
),
(
    'signature-2col',
    'Signature 2-Column (Classic)',
    'Signature 2-Col',
    'Classic 2-column balanced grid with prominent card titles',
    false,
    false,
    '{
        "shape": "rounded",
        "layout": "merged-2col",
        "borderWidth": 1,
        "borderStyle": "solid",
        "elevation": "shadow",
        "uniformHeight": 0,
        "iconSize": 24,
        "imageFit": "contain",
        "iconPadShape": "box",
        "titleSize": 11,
        "titleWeight": "bold",
        "titleColor": "#0f172a",
        "textWrap": "wrap",
        "valueBadgeStyle": "red",
        "coverageSize": 12,
        "coverageColor": "#10b981",
        "descSize": 9.5,
        "descColor": "#64748b",
        "costSize": 9.5,
        "costColor": "#b91c1c",
        "costBgColor": "#fee2e2",
        "showDescription": true,
        "showCoverage": true,
        "showCost": true,
        "bgColor": "#ffffff",
        "borderColor": "#e2e8f0",
        "textColor": "#0f172a",
        "accentColor": "#dc2626",
        "columns": 2,
        "layoutMode": "normal",
        "textDensity": "normal",
        "cardStyle": "standard",
        "rowHeight": 68
    }'::jsonb,
    NOW(),
    NOW()
),
(
    'elevated-3d',
    'Elevated 3D Card (Shadow Lift)',
    'Elevated 3D',
    'Soft cards with modern 3D elevation, subtle drop shadows',
    false,
    false,
    '{
        "shape": "soft",
        "layout": "masonry",
        "borderWidth": 1,
        "borderStyle": "solid",
        "elevation": "lift",
        "uniformHeight": 0,
        "iconSize": 22,
        "imageFit": "contain",
        "iconPadShape": "box",
        "titleSize": 10.5,
        "titleWeight": "bold",
        "titleColor": "#0f172a",
        "textWrap": "wrap",
        "valueBadgeStyle": "red",
        "coverageSize": 11,
        "coverageColor": "#10b981",
        "descSize": 9,
        "descColor": "#64748b",
        "costSize": 9,
        "costColor": "#b91c1c",
        "costBgColor": "#fee2e2",
        "showDescription": true,
        "showCoverage": true,
        "showCost": true,
        "bgColor": "#ffffff",
        "borderColor": "#e2e8f0",
        "textColor": "#0f172a",
        "accentColor": "#dc2626",
        "columns": 3,
        "layoutMode": "masonry",
        "textDensity": "compact",
        "cardStyle": "soft",
        "rowHeight": 68
    }'::jsonb,
    NOW(),
    NOW()
),
(
    'grid-tile',
    'Grid Tile (Modern Outlined)',
    'Grid Tile',
    'Clean outlined cards with circular icon pads and pill values',
    false,
    false,
    '{
        "shape": "rounded",
        "layout": "masonry",
        "borderWidth": 1,
        "borderStyle": "solid",
        "elevation": "flat",
        "uniformHeight": 0,
        "iconSize": 22,
        "imageFit": "contain",
        "iconPadShape": "circle",
        "titleSize": 10,
        "titleWeight": "bold",
        "titleColor": "#0f172a",
        "textWrap": "wrap",
        "valueBadgeStyle": "pill",
        "coverageSize": 10.5,
        "coverageColor": "#0f172a",
        "descSize": 9,
        "descColor": "#64748b",
        "costSize": 9,
        "costColor": "#0f172a",
        "costBgColor": "#e2e8f0",
        "showDescription": true,
        "showCoverage": true,
        "showCost": true,
        "bgColor": "#f8fafc",
        "borderColor": "#cbd5e1",
        "textColor": "#0f172a",
        "accentColor": "#dc2626",
        "columns": 3,
        "layoutMode": "masonry",
        "textDensity": "compact",
        "cardStyle": "outlined",
        "rowHeight": 68
    }'::jsonb,
    NOW(),
    NOW()
),
(
    'dark-signature',
    'Dark Luxury Executive',
    'Dark Luxury',
    'Executive dark slate cards with high-contrast amber highlights',
    false,
    false,
    '{
        "shape": "rounded",
        "layout": "masonry",
        "borderWidth": 1,
        "borderStyle": "solid",
        "elevation": "shadow",
        "uniformHeight": 0,
        "iconSize": 20,
        "imageFit": "contain",
        "iconPadShape": "box",
        "titleSize": 10.5,
        "titleWeight": "bold",
        "titleColor": "#ffffff",
        "textWrap": "wrap",
        "valueBadgeStyle": "red",
        "coverageSize": 11,
        "coverageColor": "#34d399",
        "descSize": 9,
        "descColor": "#94a3b8",
        "costSize": 9,
        "costColor": "#fca5a5",
        "costBgColor": "#450a0a",
        "showDescription": true,
        "showCoverage": true,
        "showCost": true,
        "bgColor": "#0f172a",
        "borderColor": "#334155",
        "textColor": "#ffffff",
        "accentColor": "#f59e0b",
        "columns": 3,
        "layoutMode": "masonry",
        "textDensity": "compact",
        "cardStyle": "standard",
        "rowHeight": 66
    }'::jsonb,
    NOW(),
    NOW()
),
(
    'dynamic-masonry',
    'Dynamic Expandable Masonry',
    'Dynamic Masonry',
    'Auto-expanding masonry grid that dynamically fits benefit boxes of varying heights',
    false,
    false,
    '{
        "shape": "rounded",
        "layout": "masonry",
        "borderWidth": 1,
        "borderStyle": "dashed",
        "elevation": "flat",
        "uniformHeight": 0,
        "iconSize": 22,
        "imageFit": "contain",
        "iconPadShape": "circle",
        "titleSize": 11,
        "titleWeight": "semibold",
        "titleColor": "#0f172a",
        "textWrap": "wrap",
        "valueBadgeStyle": "subtle",
        "coverageSize": 11.5,
        "coverageColor": "#10b981",
        "descSize": 9.5,
        "descColor": "#64748b",
        "costSize": 9.5,
        "costColor": "#475569",
        "costBgColor": "#f1f5f9",
        "showDescription": true,
        "showCoverage": true,
        "showCost": true,
        "bgColor": "#ffffff",
        "borderColor": "#e2e8f0",
        "textColor": "#0f172a",
        "accentColor": "#dc2626",
        "columns": 2,
        "layoutMode": "masonry",
        "textDensity": "comfortable",
        "cardStyle": "soft",
        "rowHeight": 75
    }'::jsonb,
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;
